# vim: ft=yaml.ansible:
---
- name: create ~/go
  file:
    path: '{{ home }}/go'
    state: directory

- name: download golang
  get_url:
    url: 'https://dl.google.com/go/go{{ golang_version }}.linux-amd64.tar.gz'
    dest: '{{ golang_download }}/go{{ golang_version }}.linux-amd64.tar.gz'
    checksum: 'sha256:{{ golang_sha256[golang_version] }}'
    mode: 0644

- name: install golang
  unarchive:
    src: '{{ golang_download }}/go{{ golang_version }}.linux-amd64.tar.gz'
    dest: '{{ golang_install }}'
    mode: 0755
    remote_src: '{{ remote_src }}'
  become: yes

- name: install dep
  package:
    name: '{{ golang_dep_pkg[ansible_distribution] }}'
    state: present
  become: yes
  when: ansible_distribution in golang_dep_pkg
