---
- name: create ~/go
  file:
    path: '{{ home }}/go'
    state: directory

- name: install golang
  package:
    name: golang
    state: present
  become: yes

- name: install dep
  package:
    name: '{{ golang_dep_pkg[ansible_os_family] }}'
    state: present
  become: yes
