---
- name: install fish shell
  package:
    name: fish
    state: present
  become: yes

- name: install fish config
  copy:
    src: config.fish
    dest: '{{ home }}/.config/fish/conf.d/config.fish'
    mode: 0664

- name: install fish functions
  copy:
    src: functions/
    dest: '{{ home }}/.config/fish/functions/'
    mode: 0664
