---
- name: install fish shell
  package:
    name: fish
    state: present
  become: yes

- name: manage ~/.config/fish
  file:
    path: '{{ home }}/.config/fish'
    state: directory
    mode: 0700

- name: manage ~/.config/fish/conf.d
  file:
    path: '{{ home }}/.config/fish/conf.d'
    state: directory
    mode: 0755

- name: install fish environment config
  copy:
    src: env.fish
    dest: '{{ home }}/.config/fish/conf.d/env.fish'
    mode: 0664

- name: install fish functions
  copy:
    src: functions/
    dest: '{{ home }}/.config/fish/functions/'
    mode: 0664
