---
- name: install fish shell
  package:
    name: fish
    state: present
  become: yes

- name: install fish config
  copy:
    src: '{{ item }}'
    dest: '{{ home }}/.config/fish/conf.d/{{ item }}'
    mode: 0664
  with_items:
    - path.fish

- name: install fish functions
  copy:
    src: '{{ item }}'
    dest: '{{ home }}/.config/fish/functions/{{ item }}'
    mode: 0664
  with_items:
    - fedora.fish
    - ubuntu.fish
