# vim: set ft=yaml.ansible:
---
- hosts: localhost
  tasks:
    - name: set user facts
      set_fact:
        home: '/home/{{ lookup("env", "USER") }}'
        user: '{{ lookup("env", "USER") }}'
      tags: [always]

- hosts: localhost
  roles:
    - role: dotfiles
      tags: [dotfiles]

    - role: base_system
      tags: [base_system]

    - role: ansible
      tags: [ansible]

    - role: ruby
      tags: [ruby]

    - role: golang
      tags: [golang]

    - role: neovim
      tags: [neovim]

    - role: terraform
      terraform_version: 0.11.7
      tags: [terraform]

    - role: packer
      packer_version: 1.2.4
      tags: [packer]

    - role: docker
      tags: [docker]

    - role: kubectl
      tags: [kubectl]

    - role: minikube
      minikube_version: v0.28.1
      tags: [minikube]

    - role: gnome-desktop
      tags: [gnome]

    - role: fish
      tags: [fish]
