# vim: set ft=yaml.ansible:
---
- hosts: localhost
  pre_tasks:
    - name: set user facts
      set_fact:
        home: '/home/{{ lookup("env", "USER") }}'
        user: '{{ lookup("env", "USER") }}'
      tags: [always]
  roles:
    - role: dotfiles
      tags: [dotfiles]

    - role: base-system
      tags: [base-system]

    - role: thermald
      tags: [thermald]

    - role: ansible
      tags: [ansible]

    - role: ruby
      tags: [ruby]

    - role: golang
      tags: [golang]

    - role: node
      tags: [node]

    - role: neovim
      tags: [neovim]

    - role: terraform
      terraform_version: 0.11.8
      tags: [terraform]

    - role: packer
      packer_version: 1.2.4
      tags: [packer]

    - role: docker
      tags: [docker]

    - role: kubectl
      tags: [kubectl]

    - role: minikube
      minikube_version: v0.28.1
      tags: [minikube]

    - role: kops
      kops_version: 1.10.0
      tags: [kops]

    - role: gnome
      tags: [gnome]

    - role: fish
      tags: [fish]

    - role: cfssl
      cfssl_version: 1.2
      tags: [cfssl]
