# vim: set ft=yaml.ansible:
---
- hosts: all
  pre_tasks:
    # TODO restore root check
    - name: set user facts
      set_fact:
        home: '/home/{{ ansible_user }}'
        user: '{{ ansible_user }}'
        download: '/home/{{ ansible_user }}/Downloads'
        remote_src: '{% if ansible_connection == "ssh" %}yes{% else %}no{% endif %}'
      tags: [always]
  roles:
    - role: base-system
      tags: [base-system]

    - role: dotfiles
      tags: [dotfiles]

    - role: thermald
      tags: [thermald]

    - role: python
      tags: [python]

    #- role: ansible
    #  tags: [ansible]

    - role: ruby
      tags: [ruby]

    - role: golang
      golang_version: 1.11.2
      tags: [golang]

    - role: node
      tags: [node]

    - role: neovim
      tags: [neovim]

    - role: terraform
      terraform_version: 0.11.8
      tags: [terraform]

    - role: packer
      packer_version: 1.2.4
      tags: [packer]

    - role: docker
      docker_compose_version: 1.23.2
      tags: [docker]

    - role: kubectl
      tags: [kubectl]

    - role: minikube
      minikube_version: v0.30.0
      tags: [minikube]

    - role: kops
      kops_version: 1.10.0
      tags: [kops]

    - role: gnome
      tags: [gnome]

    - role: fish
      tags: [fish]

    - role: cfssl
      cfssl_version: 1.2
      tags: [cfssl]

    - role: vagrant
      vagrant_version: 2.2.1
      tags: [vagrant]
