# vim: set ft=yaml.ansible:
---
- hosts: localhost
  become: yes
  tasks:
    - name: set user facts
      become: no
      tags: [always]
      set_fact:
        home: '/home/{{ lookup("env", "USER") }}'
        user: '{{ lookup("env", "USER") }}'
    - name: fail on bad user facts
      when: user == 'root' or home == '/root'
      tags: [always]
      fail: msg='User has been detected as root'

- hosts: localhost
  become: yes
  tasks:
    - import_tasks: tasks/packages.yml

    - name: install ansible
      import_role: name=ansible
      tags: [ansible]

    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/gnome.yml
    - import_tasks: tasks/neovim.yml

    - name: install ruby
      import_role: name=ruby
      tags: [ruby]

    - name: install terraform
      become: no
      tags: [terraform]
      include_role: name=terraform
      vars:
        terraform_version: 0.11.7
        terraform_download: '{{ home }}/Downloads'
        terraform_install: '{{ home }}/.local/bin' # TODO /usr/local/bin ?
    - name: install packer
      become: no
      tags: [packer]
      import_role: name=packer
      vars:
        packer_version: 1.2.4
        packer_download: '{{ home }}/Downloads'
        packer_install: '{{ home }}/.local/bin'
    - name: install kubectl
      tags: [kubectl]
      import_role: name=kubectl
    - name: install minikube
      tags: [minikube]
      import_role: name=minikube
      vars:
        minikube_version: v0.28.1
