# vim: set ft=yaml.ansible:
---
- hosts: localhost
  become: yes
  tasks:
    - name: set user facts
      become: no
      tags: [always]
      set_fact:
        home: '/home/{{ lookup("env", "USER") }}'
        user: '{{ lookup("env", "USER") }}'

    - name: fail on bad user facts
      tags: [always]
      when: user == 'root' or home == '/root'
      fail: msg='User has been detected as root'

    - import_tasks: tasks/ansible.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/gnome.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/golang.yml
    - import_tasks: tasks/packages.yml

    - name: install terraform
      become: no
      import_role: name=terraform
      vars:
        terraform_version: 0.11.7
        terraform_download: '{{ home }}/Downloads'
        terraform_install: '{{ home }}/.local/bin'

    - name: install packer
      become: no
      include_role: name=packer
      vars:
        packer_version: 1.2.4
        packer_download: '{{ home }}/Downloads'
        packer_install: '{{ home }}/.local/bin'
