# vim: set ft=yaml.ansible:
---
- hosts: localhost
  tags: [always]
  tasks:
    - name: set user facts
      become: no
      tags: [always]
      set_fact:
        home: '/home/{{ lookup("env", "USER") }}'
        user: '{{ lookup("env", "USER") }}'

- hosts: localhost
  tasks:
    - name: install base system
      import_role:
        name: base_system
      tags: [base_system]

    - name: install ansible
      import_role:
        name: ansible
      tags: [ansible]

    - import_tasks: tasks/dotfiles.yml

    - name: install ruby
      import_role:
        name: ruby
      tags: [ruby]

    - name: install golang
      import_role:
        name: golang
      tags: [golang]

    - name: install neovim
      import_role:
        name: neovim
      tags: [neovim]

    - name: install terraform
      import_role:
        name: terraform
      vars:
        terraform_version: 0.11.7
      tags: [terraform]

    - name: install packer
      import_role:
        name: packer
      vars:
        packer_version: 1.2.4
      tags: [packer]

    - name: install kubectl
      import_role:
        name: kubectl
      tags: [kubectl]

    - name: install minikube
      import_role:
        name: minikube
      vars:
        minikube_version: v0.28.1
      tags: [minikube]
