# vim: set ft=yaml.ansible:
---
- name: install ansible
  package: name={{ item }} state=present
  loop:
    - ansible
    - python2-ansible-lint
    - python2-libselinux

- name: manage /etc/ansible
  file: path=/etc/ansible state=directory owner=root group=root mode=0755

- name: manage /etc/ansible/hosts
  copy:
    content: |
      localhost ansible_connection=local
    dest: /etc/ansible/hosts
    owner: root
    group: root
    mode: 0644
