# vim: set ft=yaml.ansible:
---
- name: download terraform
  become: no
  get_url:
    url: https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
    dest: '{{ home }}/Downloads/terraform_0.11.7_linux_amd64.zip'
    checksum: sha256:6b8ce67647a59b2a3f70199c304abca0ddec0e49fd060944c26f666298e23418
    mode: 0644

- name: install terraform
  unarchive:
    src: '{{ home }}/Downloads/terraform_0.11.7_linux_amd64.zip'
    dest: '{{ home }}/.local/bin'
    mode: 0775

