---
- name: create ~/.local/bin
  file:
    path: '{{ home }}/.local/bin'
    state: directory

- name: clone ~/.vim
  git:
    repo: git@github.com:johndistasio/.vim.git
    dest: '{{ home }}/.vim'
    update: no
