---
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: install kubectl
  package:
    name: kubectl
    state: present
  become: yes
