---
- name: create ~/.local/share/themes
  file:
    path: '{{ home }}/.local/share/themes'
    state: directory

- name: install gnome-tweaks
  package:
    name: gnome-tweaks
    state: present
  become: yes

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
