---
- name: install gnome-tweaks
  package:
    name: gnome-tweaks
    state: present
  become: yes

- name: create ~/.local/share/themes
  file:
    path: '{{ home }}/.local/share/themes'
    state: directory

- name: install ant theme
  git:
    repo: git@github.com:EliverLara/Ant.git
    dest: '{{ home }}/.local/share/themes/Ant'
    version: 7fb07b2baf4c287ff30c101dbdbf3742fcee1948
    clone: yes

- name: install ant nebula theme
  git:
    repo: git@github.com:EliverLara/Ant-Nebula.git
    dest: '{{ home }}/.local/share/themes/Ant-Nebula'
    version: f9a01faded9abccd715fe5809ddd334a70fce282
    clone: yes

- name: install arc theme
  package:
    name: arc-theme
    state: present
  become: yes

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
