# vim: ft=yaml.ansible:
---
- name: install terraform
  include_role:
    name: hashicorp
  vars:
    hashicorp_app: terraform
    hashicorp_sha256: '{{ terraform_sha256[terraform_version] }}'
    hashicorp_version: '{{ terraform_version }}'
