---
- name: install apt-transport-https
  package:
    name: apt-transport-https
    state: present
  become: yes

- name: install build-essential
  package:
    name: build-essential
    state: present
  become: yes
