---
- name: install curl
  package:
    name: curl
    state: present
  become: yes

- name: install tmux
  package:
    name: tmux
    state: present
  become: yes

- name: install ctags
  package:
    name: '{{ ctags_pkg[ansible_os_family] }}'
    state: present
  become: yes

- name: install strace
  package:
    name: strace
    state: present
  become: yes

- name: install htop
  package:
    name: htop
    state: present
  become: yes

- name: install nmap
  package:
    name: nmap
    state: present
  become: yes

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
