---
- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: install docker-ce
  package:
    name: docker-ce
    state: present
  become: yes

- name: enable docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
  become: yes

- name: download and install docker-compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64'
    dest: '{{ home }}/.local/bin/docker-compose'
    checksum: 'sha256:{{ docker_compose_sha256[docker_compose_version] }}'
    mode: 0775
