---
- name: add docker-ce apt repository key
  apt_key:
    url: '{{ docker_repo_gpg_key }}'
    state: present
  become: yes

- name: add docker-ce apt repository
  apt_repository:
    repo: 'deb [arch=amd64] {{ docker_repo_url }} {{ ansible_lsb["codename"] }} stable'
    state: present
  become: yes
